### PR TITLE
fix: Use make() to initialise array of Policy and Role instead of leaving it uninitalised

### LINKED ISSUE #217: Policies and roles list should return empty array if list is empty
**Describe the bug**

Policies and roles list are returning `null` instead of empty list if all elements are filtered out.
This breaks api contract and generates an error in php client (for example)

**Reproducing the bug**

1. Send a GET request to `/engines/acp/ory/glob/policies` on a newly created keto server
2. Response is `null` instead of `[]`

### PR DESCRIPTION
**Pull request by xlanor**
Fixes #217 
This is an ongoing issue in `encoding/json`, whereby if an uninitialised array (such as policies, which is declared as `var p Policies`, or roles, which is declared as `var p Roles`) is attempted to be encoded using `json.Marshal`, it results in a `nil` value being returned instead of `[]`.

Given that json doesn't appear to be merging the currently open PR to add an option to return nil as [] or {} in when json.Marshal is used anytime soon, this patch should fix that.

I've updated the tests in filter_test.go and filter_helper_test.go to replace the expected nil values with the relevant empty Role/Policy object.

## Related issue

#217
https://github.com/golang/go/issues/27589
## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security. vulnerability, I
      confirm that I got green light (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](docs/docs).

## Further comments

Below is the tracing process that I posted on #217 

I've been tracing this bug because it also affects us at work, and I've traced it to this
`func (h *Handler) List(factory func(context.Context, *http.Request, httprouter.Params) (*ListRequest, error)) httprouter.Handle` in `storage/handler.go` returns a `h.h.Write(w, r, l.Filter(m).Value)`, and in this case, `l.Filter(m).Value` returns `*storage.Policies`, which is declared as a type of []Policy .

`h`, in this case, which is a type of `herodot.Writer`, an interface, in this particular function, is a `herodot.JSONWriter`, and   `Write` in this case calls `WriteCode` [here](https://github.com/ory/herodot/blob/master/json.go). This tells me that there's an issue with `encoding/json`'s  `json.Marshal(e)`, where `e` refers to `l.Filter(m).Value`.

I believe this is due to https://github.com/golang/go/issues/27589, and a proposal has been made to modify `encoding/json` that is still under going review [here](https://go-review.googlesource.com/c/go/+/136761/) and awaiting a PR at https://github.com/golang/go/issues/37711.

At this point, I'm wondering if I should submit a PR to `ory/herodot`, to do the checking in `func WriteCode`. If it is a shared library, do you think that this will affect other projects that ory has?

There's a quick fix, as can be seen from https://github.com/CosmWasm/go-cosmwasm/pull/75, to quickly check the value, and if it's nil, do not even proceed with `JSON.Marshal`. This might actually be the fastest way to fix this, but I'm unsure about the potential impact, given that herodot is a shared repository.

Ultimately, the issue lies in `func ListByQuery` in `storage/handler.go`, which declares var res Roles and var res Policies without explicitly initialising them, as well as `func rolesList` and `func policiesList` in `engine/ladon/handler.go`, which does the same.

### CODE REVIEW

File: engine/ladon/handler.go [hunk 1]
```diff
@@ -290,8 +290,7 @@ func (e *Engine) Register(r *httprouter.Router) {
 }
 
 func (e *Engine) rolesList(ctx context.Context, r *http.Request, ps httprouter.Params) (*kstorage.ListRequest, error) {
-	var p kstorage.Roles
-
+	p := make([]kstorage.Role, 0)
```
Comment (aeneasr) [inline engine/ladon/handler.go:293]: It is possible to make types that have an underlying type of a slice or map:

```suggestion
	p := make(kstorage.Roles, 0)
```

File: engine/ladon/handler.go [hunk 2]
```diff
@@ -428,8 +427,8 @@ func (e *Engine) policiesCreate(ctx context.Context, r *http.Request, ps httprou
 }
 
 func (e *Engine) policiesList(ctx context.Context, r *http.Request, ps httprouter.Params) (*kstorage.ListRequest, error) {
-	var p kstorage.Policies
 
+	p := make([]kstorage.Policy, 0)
```
Comment (aeneasr) [inline engine/ladon/handler.go:431]:
```suggestion
	p := make(kstorage.Policies, 0)
```

File: storage/filter_helper_test.go [hunk 3]
```diff
@@ -1,7 +1,7 @@
 package storage
```
Comment (aeneasr) [inline storage/filter_helper_test.go:1]: Revert the changes in this file :)

File: storage/handler.go [hunk 4]
```diff
@@ -84,17 +84,17 @@ func (l *ListRequest) Filter(m map[string][]string) *ListRequest {
 
 func ListByQuery(l *ListRequest, m map[string][]string) {
 	switch val := l.Value.(type) {
-	case *Roles:
-		var res Roles
+	case *[]Role:
```
Comment (aeneasr) [inline storage/handler.go:87]:
```suggestion
	case *Roles:
```

File: storage/handler.go [hunk 5]
```diff
@@ -84,17 +84,17 @@ func (l *ListRequest) Filter(m map[string][]string) *ListRequest {
...
 		for _, role := range *val {
 			filteredRole := role.withMembers(m["member"]).withIDs(m["id"])
 			if filteredRole != nil {
 				res = append(res, *filteredRole)
 			}
 		}
 		l.Value = &res
-	case *Policies:
-		var res Policies
+	case *[]Policy:
```
Comment (aeneasr) [inline storage/handler.go:96]:
```suggestion
	case *Policies:
```

File: storage/handler.go [hunk 6]
```diff
@@ -84,17 +84,17 @@ func (l *ListRequest) Filter(m map[string][]string) *ListRequest {
 
 func ListByQuery(l *ListRequest, m map[string][]string) {
 	switch val := l.Value.(type) {
-	case *Roles:
-		var res Roles
+	case *[]Role:
+		res := make([]Role, 0)
```
Comment (aeneasr) [inline storage/handler.go:88]:
```suggestion
		res := make(Roles, 0)
```

File: storage/handler.go [hunk 7]
```diff
@@ -84,17 +84,17 @@ func (l *ListRequest) Filter(m map[string][]string) *ListRequest {
...
 			filteredRole := role.withMembers(m["member"]).withIDs(m["id"])
 			if filteredRole != nil {
 				res = append(res, *filteredRole)
 			}
 		}
 		l.Value = &res
-	case *Policies:
-		var res Policies
+	case *[]Policy:
+		res := make([]Policy, 0)
```
Comment (aeneasr) [inline storage/handler.go:97]:
```suggestion
		res := make(Policies, 0)
```

**Review by aeneasr — COMMENTED** [review]
Awesome, thank you for your contribution! This looks pretty good but I have some ideas how to improve it further :)

**Comment by xlanor** [comment]
Ah, I didn't know that! It's late here now, I will push the changes that you've suggested tomorrow

File: storage/filter_helper_test.go (hunk 3 above)
Comment (xlanor) [reply storage/filter_helper_test.go]: Apart from reverting this, I have also changed the expected nil values to match the empty policies/roles that is returned now.

**Comment by xlanor** [comment]
@aeneasr , The requested changes have been made!

**Review by aeneasr — APPROVED** [review]
Awesome 🎉 

Thank you for your contribution!
