### PR TITLE
fix: readonly UUID mapping inserts

### LINKED ISSUE #1076: Querying ListRelationTuples with any subject results in row being added to keto_uuid_mappings
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Querying ListRelationTuples with an unknown subject results in row being added to keto_uuid_mappings.  Beyond just database bloat, this is a potential DOS attack vector.  Something along the lines of repeatedly querying the endpoint with a randomly generated subject could fill up storage leading to a DOS

### Reproducing the bug

1. Run keto serves with a persistent store (mysql or postgres)
2. Query the keto_uuid_mappings table directly for a subject not already persisted as a relationship tuple.  A random uuid would work well.
`select id, string_representation  from public.keto_uuid_mappings where string_representation = '940099dd-fc53-5c7f-a684-98c05e4bdca6'`
**Note that there are no rows returned**
3. Using the keto cli, execute a relation-tuple get command for a valid namespace and the unknown subject used above.
`keto relation-tuple get --namespace books --subject-id 940099dd-fc53-5c7f-a684-98c05e4bdca6`
**Note that no tuples are returned**
4. Query the keto_uuid_mappings table directly for the subject used above.
`select id, string_representation  from public.keto_uuid_mappings where string_representation = '940099dd-fc53-5c7f-a684-98c05e4bdca6'`
**Note that a single row is now returned**

Expected: No rows would be added.
Actual: A row was added for the unknown subject.

### Relevant log output

_No response_

### Relevant configuration

_No response_

### Version

0.10.0-alpha.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Binary

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by hperl**
This PR adds a read-only version of the UUID mapper that performs the mappings but does not write them to the database. This mapper suffices for all endpoints that do not add new tuples to the database, and is obviously much faster that the read-write version of the mapper.

Tests were added to show that the read-only mapper behaves the same as the read-write version, if all information is already mapped.

## Related issue(s)

Fixes #1076

## Checklist

- [ ] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [ ] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [ ] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [ ] I have read the [security policy](../security/policy).
- [ ] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [ ] I have added tests that prove my fix is effective or that my feature
      works.
- [ ] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

**Review by zepatrik — COMMENTED** [review]
Nice, I would just like to add one test that ensures the UUIDs are actually (not) persisted depending on the mapper.

File: internal/relationtuple/uuid_mapping_test.go [hunk 1]
```diff
@@ -321,4 +321,31 @@ func TestMapper(t *testing.T) {
...
+
+		t.Run("case=ro manager does not insert into DB", func(t *testing.T) {
+			unmapped := &ketoapi.RelationQuery{Object: pointerx.Ptr("unmapped object")}
+			mapped, err := roMapper.FromQuery(ctx, unmapped)
+			require.NoError(t, err)
+			assert.NotNil(t, mapped.Object)
+
+			reUnmapped, err := roMapper.ToQuery(ctx, mapped)
+			require.NoError(t, err)
+			assert.Empty(t, reUnmapped.Object)
```
Comment (zepatrik) [inline internal/relationtuple/uuid_mapping_test.go:337]: Hmm, maybe this case should instead return an error, as the RO mapper is unable to do the mapping? Just to not have bugs later on.

**Review by zepatrik — APPROVED** [review]
