### PR TITLE
fix: hide relation tuples with deleted namespace

### LINKED ISSUE #946: Deleting a namespace that contains relation tuples results in GetRelationTuples returning "not found"
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When I delete a namespace that has relation tuples, subsequent calls to GetRelationTuples returns in a "not found" (for the deleted namespace).

Instead, GetRelationTuples should just filter out the tuples for which the namespace was deleted.

### Reproducing the bug

1. Create namespace "users"
2. Create relation tuple "users:foo#id@123"
3. Delete namespace "users"
4. GetRelationTuples

--> Throws "not found"

### Relevant log output

_No response_

### Relevant configuration

_No response_

### Version

v0.8.0

### On which operating system are you observing this issue?

_No response_

### In which environment are you deploying?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by hperl**
Fixes #946

### CODE REVIEW

File: internal/e2e/helpers.go [hunk 1]
```diff
@@ -26,7 +26,51 @@ import (
...
+		}
+	})
+}
+
+func (m *namespaceTestManager) remove(t *testing.T, id int32) {
+	newNamespaces := make([]*namespace.Namespace, 0, len(m.nspaces))
+	for _, n := range m.nspaces {
+		if n.ID != id {
+			newNamespaces = append(newNamespaces, n)
+			break
```
Comment (zepatrik) [inline internal/e2e/helpers.go:66]: This does not seem right? You want to continue after the first one that was appended right?

```suggestion
```

**Review by zepatrik — CHANGES_REQUESTED** [review]
Very nice, just some minor improvements :+1:

**Review by zepatrik — APPROVED** [review]
