### PR TITLE
fix: subject expansion is terminated unexpectedly

### LINKED ISSUE #1255: Subject expansion failed when depth exceeds 2
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Given the namespace definition
```ts
class Role implements Namespace {
	related: {
		perms: SubjectSet<Role, "perms">[]
	}
}
```
and the relation tuples:
```
"Role:a#perms@Role:b#perms",
"Role:b#perms@Role:c#perms",
"Role:c#perms@Role:d#perms",
"Role:d#perms@get",
```

The check "Role:a#perms@get" will fail.

### Reproducing the bug

```go
package check_test

import (
	"context"
	"testing"

	"github.com/sirupsen/logrus"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"go.uber.org/goleak"

	"github.com/ory/keto/internal/check"
	"github.com/ory/keto/internal/check/checkgroup"
	"github.com/ory/keto/internal/driver/config"
	"github.com/ory/keto/internal/namespace"
	"github.com/ory/keto/internal/schema"
)

func TestSubjectExpansion(t *testing.T) {
	var rawns = `
	import { Namespace, SubjectSet, Context } from '@ory/keto-namespace-types';
	
	class Role implements Namespace {
	  related: {
		perms: SubjectSet<Role, "perms">[]
	  }
	}`

	nss, err := schema.Parse(rawns)
	require.True(t, err == nil)
	namespaces := make([]*namespace.Namespace, len(nss))
	for i, ns := range nss {
		ns := ns
		namespaces[i] = &ns
	}

	reg := newDepsProvider(t, namespaces)
	reg.Logger().Logger.SetLevel(logrus.InfoLevel)

	insertFixtures(t, reg.RelationTupleManager(), []string{
		"Role:a#perms@Role:b#perms",
		"Role:b#perms@Role:c#perms",
		"Role:c#perms@Role:d#perms",
		"Role:d#perms@get",
	})

	testCases := []struct {
		query         string
		expected      checkgroup.Result
		expectedPaths []path
	}{{
		query:    "Role:d#perms@get",
		expected: checkgroup.ResultIsMember,
	}, {
		query:    "Role:c#perms@get",
		expected: checkgroup.ResultIsMember,
	}, {
		query:    "Role:b#perms@get",
		expected: checkgroup.ResultIsMember,
	}, { // This case will fail
		query:    "Role:a#perms@get",
		expected: checkgroup.ResultIsMember,
	}}

	t.Run("suite=testcases", func(t *testing.T) {
		ctx := context.Background()
		reg.Config(ctx).Set(config.KeyLimitMaxReadDepth, 10)
		e := check.NewEngine(reg)
		defer goleak.VerifyNone(t, goleak.IgnoreCurrent())

		for _, tc := range testCases {
			t.Run("case="+tc.query, func(t *testing.T) {
				rt := tupleFromString(t, tc.query)

				res := e.CheckRelationTuple(ctx, rt, 100)
				require.NoError(t, res.Err)
				t.Logf("tree:\n%s", res.Tree)
				assert.Equal(t, tc.expected.Membership, res.Membership)

				if len(tc.expectedPaths) > 0 {
					for _, path := range tc.expectedPaths {
						assertPath(t, path, res.Tree)
					}
				}
			})
		}
	})
}
```

### Relevant log output

```shell
=== RUN   TestSubjectExpansion
time=2023-02-24T19:45:04+08:00 level=info msg=No tracer configured - skipping tracing setup audience=application service_name=Ory Keto service_version=testing
=== RUN   TestSubjectExpansion/suite=testcases
=== RUN   TestSubjectExpansion/suite=testcases/case=Role:d#perms@get
    /keto/internal/check/check_test.go:80: tree:
        ∋ Role:5d0ab373-34e6-5449-9217-196aa2ef5d76#perms@01338e40-ba98-5539-a9ee-856b0223c9b1️
=== RUN   TestSubjectExpansion/suite=testcases/case=Role:c#perms@get
    /keto/internal/check/check_test.go:80: tree:
=== RUN   TestSubjectExpansion/suite=testcases/case=Role:b#perms@get
    /keto/internal/check/check_test.go:80: tree:
=== RUN   TestSubjectExpansion/suite=testcases/case=Role:a#perms@get
    /keto/internal/check/check_test.go:80: tree:
    /keto/internal/check/check_test.go:81:
        	Error Trace:	/keto/internal/check/check_test.go:81
        	Error:      	Not equal:
        	            	expected: 1
        	            	actual  : 2
        	Test:       	TestSubjectExpansion/suite=testcases/case=Role:a#perms@get
--- FAIL: TestSubjectExpansion (0.02s)
    --- FAIL: TestSubjectExpansion/suite=testcases (0.00s)
        --- PASS: TestSubjectExpansion/suite=testcases/case=Role:d#perms@get (0.00s)
        --- PASS: TestSubjectExpansion/suite=testcases/case=Role:c#perms@get (0.00s)
        --- PASS: TestSubjectExpansion/suite=testcases/case=Role:b#perms@get (0.00s)
        --- FAIL: TestSubjectExpansion/suite=testcases/case=Role:a#perms@get (0.00s)
FAIL
FAIL	github.com/ory/keto/internal/check	0.811s
```

### Relevant configuration

_No response_

### Version

master

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

None

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by stonelgh**
This change fixes the issue that subject expansion will fail if the depth exceeds 2.

## Related issue(s)

closes #1255

## Checklist

- [x] I have read the [contributing guidelines](../blob/master/CONTRIBUTING.md).
- [x] I have referenced an issue containing the design document if my change
      introduces a new feature.
- [x] I am following the
      [contributing code guidelines](../blob/master/CONTRIBUTING.md#contributing-code).
- [x] I have read the [security policy](../security/policy).
- [x] I confirm that this pull request does not address a security
      vulnerability. If this pull request addresses a security vulnerability, I
      confirm that I got the approval (please contact
      [security@ory.sh](mailto:security@ory.sh)) from the maintainers to push
      the changes.
- [x] I have added tests that prove my fix is effective or that my feature
      works.
- [x] I have added or changed [the documentation](https://github.com/ory/docs).

### CODE REVIEW

File: internal/check/engine.go [hunk 1]
```diff
@@ -137,7 +137,12 @@ func (e *Engine) checkExpandSubject(r *relationTuple, restDepth int) checkgroup.
 
 		// If not, we must go another hop:
 		for _, result := range results {
-			innerCtx, visited = graph.CheckAndAddVisited(innerCtx, result.To.Subject)
+			sub := &relationtuple.SubjectSet{
+				Namespace: result.To.Namespace,
+				Object:    result.To.Object,
+				Relation:  result.To.Relation,
+			}
+			innerCtx, visited = graph.CheckAndAddVisited(innerCtx, sub)
```
Comment (zepatrik) [inline internal/check/engine.go:145]: Good catch, at this point `result.To.Subject` is the same for all results: https://github.com/ory/keto/blob/db59a33ed171fbb56ed81c31e822199e1011910f/internal/persistence/sql/traverser.go#L108

**Review by zepatrik — APPROVED** [review]
Thanks a lot, very nice find :+1:

**Review by hperl — APPROVED** [review]
Very nice, thanks! :tada:
